//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.269
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IFileDownloadService")]
    public interface IFileDownloadService {
        
        // CODEGEN: Generating message contract since the wrapper name (FileDownloadMessage) of message FileDownloadMessage does not match the default value (DownloadFile)
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileDownloadService/DownloadFile", ReplyAction="http://tempuri.org/IFileDownloadService/DownloadFileResponse")]
        Client.ServiceReference1.FileDownloadReturnMessage DownloadFile(Client.ServiceReference1.FileDownloadMessage request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileDownloadMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileDownloadMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Contract.FileMetaData FileMetaData;
        
        public FileDownloadMessage() {
        }
        
        public FileDownloadMessage(Contract.FileMetaData FileMetaData) {
            this.FileMetaData = FileMetaData;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FileDownloadReturnMessage", WrapperNamespace="http://tempuri.org/", IsWrapped=true)]
    public partial class FileDownloadReturnMessage {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://tempuri.org/")]
        public Contract.FileMetaData DownloadedFileMetadata;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://tempuri.org/", Order=0)]
        public System.IO.Stream FileByteStream;
        
        public FileDownloadReturnMessage() {
        }
        
        public FileDownloadReturnMessage(Contract.FileMetaData DownloadedFileMetadata, System.IO.Stream FileByteStream) {
            this.DownloadedFileMetadata = DownloadedFileMetadata;
            this.FileByteStream = FileByteStream;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileDownloadServiceChannel : Client.ServiceReference1.IFileDownloadService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileDownloadServiceClient : System.ServiceModel.ClientBase<Client.ServiceReference1.IFileDownloadService>, Client.ServiceReference1.IFileDownloadService {
        
        public FileDownloadServiceClient() {
        }
        
        public FileDownloadServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileDownloadServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDownloadServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileDownloadServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Client.ServiceReference1.FileDownloadReturnMessage Client.ServiceReference1.IFileDownloadService.DownloadFile(Client.ServiceReference1.FileDownloadMessage request) {
            return base.Channel.DownloadFile(request);
        }
        
        public Contract.FileMetaData DownloadFile(Contract.FileMetaData FileMetaData, out System.IO.Stream FileByteStream) {
            Client.ServiceReference1.FileDownloadMessage inValue = new Client.ServiceReference1.FileDownloadMessage();
            inValue.FileMetaData = FileMetaData;
            Client.ServiceReference1.FileDownloadReturnMessage retVal = ((Client.ServiceReference1.IFileDownloadService)(this)).DownloadFile(inValue);
            FileByteStream = retVal.FileByteStream;
            return retVal.DownloadedFileMetadata;
        }
    }
}
